---
- name: Install software common
  apt:
    name: software-properties-common
    state: present
    update_cache: true
  
- name: Set ppa repository
  apt_repository:
    repo: "{{ externalRepo }}"
    update_cache: true
  when: ansible_distribution != 'Debian'

- name: Install php
  apt:
    name: " {{ item }} "
    state: present
  with_items:
    - "{{ php_packages }}"

- name: Enable php-fpm
  ansible.builtin.systemd:
    name: "{{ php_daemon }}"
    state: started
    enabled: true