---
- name: load variables based on OS type
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - 'vars/{{ ansible_os_family}}-{{ ansible_distribution_major_version }}.yml'
      - 'vars/{{ ansible_os_family }}.yml'
      skip: true

- name: Define packages to install
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: Set php daemon
  set_fact:
    php_daemon: "{{ __php_daemon }}"
  when: php_daemon is not defined 

- name: set repository
  set_fact:
    externalRepo: "{{ __externalRepo }}"
  when: externalRepo is not defined
